apps/user/views.py
from flask import Blueprint, jsonify, render_template, redirect, url_for, request, flash, g, session, Response, flash
from apps.user.models import my_db




user_app = Blueprint("user_app", import_name=__name__, url_prefix="/user")


@user_app.route("/login", methods=['GET', "POST"], endpoint="user_login")
def user_login():
    if request.method == "GET":
        return render_template('login/login.html')
    if request.method == "POST":
        try:
            user_name = request.form.get("user_name")
            password = request.form.get("password")
            login_status = request.form.get("login_status")
            # print(login_status)
            one_user = my_db.query_one(f"select * from user where username='{user_name}' and password='{password}'")
            if one_user:
                session['user_name'] = user_name
                if login_status:
                    session.permanent = True
                return redirect(url_for("log_app.shengsheng_index"))
        except Exception as e:
            print(e)
        flash(message="账号或密码错误,请重新输入", category="warning")
        return render_template('login/login.html')


@user_app.get("/logout", endpoint="user_logout")
def user_logout():
    try:
        if "user_name" in session:
            session.clear()
        return redirect(url_for("user_app.user_login"))
    except Exception as e:
        return jsonify({"status": 10404, "msg": "异常"})


@user_app.route("/login/test", methods=['GET', "POST"], endpoint="user_login111")
def user_login111():
    if request.method == "GET":
        return jsonify({"google": "string"})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/svg+xml" href="{{ url_for("static",filename="image/user.png") }}"/>
    <link rel="stylesheet" href="{{ url_for("static",filename="css/bootstrap-switch.min.css") }}">
    <link href="{{ url_for("static",filename="css/bootstrap.min.css") }}" rel="stylesheet">
    <script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/bootstrap-switch.min.js') }}"></script>
    <script src="{{ url_for("static",filename="js/highcharts.js") }}"></script>

    <title>省省日志</title>
</head>
<body>

<div class="base_ul">
    <ul>
        <li>用户: <span>{{ g.user_name }}</span></li>
    </ul>
</div>
<div class="base_ul_right">
    <a href="{{ url_for("user_app.user_logout") }}">
        <button type="submit" class="btn btn-primary mb-2" style="float: right">退出</button>
    </a>

</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for("log_app.shengsheng_index") }}">首页</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item dropdown" style="margin-right: 20px">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-expanded="false">
                    统计图查询
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                    <a class="dropdown-item" href="{{ url_for('log_app.query_log_record_chart') }}">日志统计图</a>
                    <a class="dropdown-item" href="{{ url_for('log_app.query_version_count_chart') }}">版本统计图</a>
                </div>

            </li>

        </ul>

        <form class="form-inline my-2 my-lg-0" action="{{ url_for("log_app.query_log_record_by_code") }}" method="post">
            <input class="form-control mr-sm-3" type="text" placeholder="激活码" value="{{ code }}" aria-label="Search"
                   name="code" required style="width: 60%">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">查询日志</button>
        </form>
    </div>
</nav>
<div>
    {% block index_info %}{% endblock %}
    {% block query_log_record_logs %}{% endblock %}
    {% block log_record_chart %}{% endblock %}
    {% block version_code_chart %}{% endblock %}

</div>

</body>
<style>
    body {
        width: 80%;
        height: auto;
        margin: 10px auto;
    }

    table {
        table-layout: fixed
    }

    table tr {
        line-height: 15px;

        border: 1px solid #ccc;

    }

    td {
        border: 1px solid #ccc;
        word-break: keep-all; /* 不换行 */

        white-space: nowrap; /* 不换行 */

        overflow: hidden; /* 内容超出宽度时隐藏超出部分的内容 */

        text-overflow: ellipsis; /* 当对象内文本溢出时显示省略标记(...) ；需与overflow:hidden;一起使用*/

    }

    .base_ul {
        width: 80%;
        height: 30px;
        margin: 10px auto;
        float: left;
    }

    .base_ul_right {
        width: 20%;
        height: 30px;
        margin: 10px auto;
        float: right;
    }

    .base_ul ul {

        list-style: none;
        padding: 0;
    }

    .base_ul li {
        line-height: 20px;
        float: left;

        margin-right: 30px;
        margin-top: 10px;
    }

    .base_ul span {
        color: #bd2130;
    }

</style>

</html>